name: "SCP SSH Action"
description: "Runs a remote command via SSH"

runs:
  using: "composite"
  steps:
    - name: Setup SSH Key
      shell: bash
      run: |
        echo "-------------------"
        echo "AAAAAAAAAAAAAAAA" > ~/test.txt
        echo "-------------------"
        echo "${{ inputs.SSH_KEY }}" >> ~/test.txt
        echo "${{ inputs.HOST_NAME }}"  >> ~/test.txt
        echo "${{ inputs.COMMAND }}"  >> ~/test.txt
        echo "-------------------"
        cat ~/test.txt
        echo "-------------------"
        base64 ./test.txt > ./encoded.txt
        echo "-------------------"
        tail ~/encoded.txt
        echo "-------------------"

inputs:
  HOST_NAME:
    description: "Remote hostname"
    required: true
  USER_NAME:
    description: "Remote username"
    required: true
  SSH_KEY:
    description: "Private SSH key"
    required: true
  COMMAND:
    description: "Command to run on the remote host"
    required: true
